export const STEEPVCOLOR = [
  {
    value: 'Social',
    bgColor: '#fff1b8',
    textColor: '#ad6800',
  },
  {
    value: 'Technological',
    bgColor: '#ffccc7',
    textColor: '##a8071a',
  },
  {
    value: 'Economic',
    bgColor: '#efdbff',
    textColor: '#391085',
  },
  {
    value: 'Environmental',
    bgColor: '#ffd6e7',
    textColor: '#9e1068',
  },
  {
    value: 'Political',
    bgColor: '#f4ffb8',
    textColor: '#5b8c00',
  },
  {
    value: 'Values',
    bgColor: '#d9f7be',
    textColor: '#237804',
  },
];

export const SSCOLOR = [
  {
    value: 'Poverty and inequality',
    bgColor: '#bae7ff',
    textColor: '#0050b3',
  },
  {
    value: 'Governance',
    bgColor: '#d9f7be',
    textColor: '#237804',
  },
  {
    value: 'Resilience',
    bgColor: '#ffccc7',
    textColor: '##a8071a',
  },
  {
    value: 'Environment',
    bgColor: '#ffd6e7',
    textColor: '#9e1068',
  },
  {
    value: 'Energy',
    bgColor: '#fff1b8',
    textColor: '#ad6800',
  },
  {
    value: 'Gender equality',
    bgColor: '#f4ffb8',
    textColor: '#5b8c00',
  },
  {
    value: 'Digitalisation',
    bgColor: '#efdbff',
    textColor: '#391085',
  },
  {
    value: 'Innovation',
    bgColor: '#b5f5ec',
    textColor: '#006d75',
  },
  {
    value: 'Development Financing',
    bgColor: '#ffccc7',
    textColor: '#a8071a',
  },
  {
    value: 'Others',
    bgColor: '#ffccc7',
    textColor: '#a8071a',
  },
];

export const HorizonColor = [
  {
    value: 'Immediate 2022-2025',
    bgColor: '#ffccc7',
    textColor: '#a8071a',
  },
  {
    value: 'Medium-term 2025-2029',
    bgColor: '#bae7ff',
    textColor: '#0050b3',
  },
  {
    value: 'Long-term 2029-2032',
    bgColor: '#d9f7be',
    textColor: '#237804',
  },
  {
    value: 'Unknown',
    bgColor: '#E9ECF6',
    textColor: '#000',
  },
];

export const CountryList = [
  'UNDP Nordic Representation Office (Copenhagen, Denmark)',
  'UNDP Office in Geneva (Geneva, Switzerland)',
  'UNDP Representation Office Germany (Bonn, Germany)',
  'UNDP Representation Office in Brussels (Brussels, Belgium)',
  'UNDP Representation Office in Japan (Tokyo, Japan)',
  'UNDP Washington Representation Office (Washington, USA)',
  'Global Centre for Technology, Innovation and Sustainable Development (Singapore)',
  'Istanbul International Center for Private Sector in Development (Istanbul, Turkey)',
  'Nairobi Global Centre on Resilient Ecosystems and Desertification (Nairobi, Kenya)',
  'Oslo Governance Centre (Oslo, Norway)',
  'UNDP Seoul Policy Centre for Knowledge Exchange through SDG Partnerships (Seoul, Republic of Korea)',
  'BERA',
  'BMS',
  'BPPS',
  'Crisis Bureau (CB)',
  'Executive Office (ExO)',
  'Human Development Report Office (HDRO)',
  'Independent Evaluation Office (IEO)',
  'Office of Audit and Investigations (OAI)',
  'Regional Bureau for Africa, New York, USA',
  'Regional Bureau for Arab States, New York, USA',
  'Regional Bureau for Asia and the Pacific, New York',
  'Regional Bureau for Europe and the CIS, New York, USA',
  'Regional Bureau for Latin America and the Caribbean, New York, USA',
  'Angola',
  'Benin',
  'Botswana',
  'Burkina Faso',
  'Burundi',
  'Cameroon',
  'Central African Republic',
  'Chad',
  'Comoros',
  'Congo',
  'Côte d’Ivoire',
  'Democratic Republic of Congo',
  'Equatorial Guinea',
  'Eritrea',
  'Eswatini',
  'Ethiopia',
  'Gabon',
  'Gambia',
  'Ghana',
  'Guinea',
  'Guinea-Bissau',
  'Kenya',
  'Lesotho',
  'Liberia',
  'Madagascar',
  'Malawi',
  'Mali',
  'Mauritania',
  'Mauritius',
  'Mozambique',
  'Namibia',
  'Niger',
  'Nigeria',
  'Regional Hub: Dakar, Senegal',
  'Regional Hub: Nairobi, Kenya',
  'Regional Hub: Pretoria, South Africa',
  'Regional Service Centre: Addis Ababa, Ethiopia',
  'Republic of Cape Verde',
  'Republic of South Sudan',
  'Rwanda',
  'Sao Tome and Principe',
  'Senegal',
  'Seychelles',
  'Sierra Leone',
  'South Africa',
  'Tanzania',
  'Togo',
  'Uganda',
  'Zambia',
  'Zimbabwe',
  'Afghanistan',
  'Bangladesh',
  'Bhutan',
  'Brunei Darussalam',
  'Cambodia',
  'China',
  'Cook Islands',
  'DPRK',
  'Federated States of Micronesia',
  'Fiji MCO',
  'India',
  'Indonesia',
  'Iran',
  'Kiribati',
  'Lao PDR',
  'Malaysia MCO',
  'Maldives',
  'Marshall Islands',
  'Mongolia',
  'Myanmar',
  'Nauru',
  'Nepal',
  'Niue',
  'Pakistan',
  'Palau',
  'Philippines',
  'PNG',
  'Regional Hub: Bangkok, Thailand',
  'Samoa MCO',
  'Singapore',
  'Solomon Islands',
  'Sri Lanka',
  'Thailand',
  'Timor Leste',
  'Tokelau',
  'Tonga',
  'Tuvalu',
  'Vanuatu',
  'Viet Nam',
  'Algeria',
  'Bahrain',
  'Djibouti',
  'Egypt',
  'Iraq',
  'Jordan',
  'Kuwait',
  'Lebanon',
  'Libya',
  'Morocco',
  'People',
  'Prog for Palestinian',
  'Regional Hub: Amman, Jordan',
  'Republic of the',
  'Republic of the Sudan',
  'Saudi Arabia',
  'Somalia',
  'Syria',
  'Tunisia',
  'Yemen',
  'Albania',
  'Armenia',
  'Azerbaijan',
  'Bosnia and Herzegovina',
  'Cyprus (project office)',
  'Georgia',
  'Kazakhstan',
  'Kosovo (as per UNSCR 1244)',
  'Kyrgyzstan',
  'Moldova',
  'North Macedonia',
  'Regional Hub: Istanbul, Turkey',
  'Republic of Belarus',
  'Republic of Montenegro',
  'Serbia',
  'Tajikistan',
  'Turkey',
  'Turkmenistan',
  'Ukraine',
  'Uzbekistan',
  'Anguilla',
  'Antigua and Barbuda',
  'Argentina',
  'Aruba',
  'Barbados',
  'Belize',
  'Bermuda',
  'Bolivia',
  'Brazil',
  'Cayman Islands',
  'Chile',
  'Colombia',
  'Costa Rica',
  'Cuba',
  'Curacao and Sint Maarten',
  'Dom. Republic',
  'Ecuador',
  'El Salvador',
  'Grenada',
  'Guatemala',
  'Guyana',
  'Guyana-Suriname',
  'Haiti',
  'Honduras',
  'Jamaica',
  'Mexico',
  'Montserrat',
  'Nicaragua',
  'Panama',
  'Paraguay',
  'Peru',
  'Regional Centre: Panama City, Panama',
  'Saint Kitts and Nevis',
  'Saint Lucia and Saint Vincent',
  'Suriname',
  'The Bahamas',
  'the British Virgin Islands',
  'the Commonwealth of Dominica',
  'the Grenadines',
  'Trinidad & Tobago',
  'Turks and Caicos Islands',
  'Uruguay',
  'Venezuela',
];
